import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from 'docx';
import { ReportData } from './types';

export async function generateDocxReportBuffer(data: ReportData): Promise<Buffer> {
  const tableRows: TableRow[] = [];

  const columns = data.columns && data.columns.length > 0
    ? data.columns
    : ['Student Name', 'Student Code', 'Class', 'Department', 'Attended', 'Total', 'Percentage'];

  // 1. Table Header Row
  tableRows.push(
    new TableRow({
      tableHeader: true,
      children: columns.map(
        (col) =>
          new TableCell({
            width: { size: Math.floor(100 / columns.length), type: WidthType.PERCENTAGE },
            shading: { fill: '4338CA' },
            margins: { top: 100, bottom: 100, left: 150, right: 150 },
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: col, bold: true, color: 'FFFFFF', size: 20 })],
              }),
            ],
          })
      ),
    })
  );

  // 2. Data Rows
  data.rows.forEach((rowObj) => {
    let rowValues: any[] = [];

    if (Array.isArray(rowObj)) {
      rowValues = rowObj;
    } else {
      const sName = rowObj.studentName || data.metadata?.studentName || '';
      const sCode = rowObj.studentCode || data.metadata?.studentCode || '';
      const cName = rowObj.className || data.metadata?.className || '';
      const dept = rowObj.department || data.metadata?.department || '';

      const attended = rowObj.attended !== undefined ? String(rowObj.attended) : '';
      const total = rowObj.total !== undefined ? String(rowObj.total) : '';

      let pctStr = '';
      if (rowObj.percentage !== undefined) {
        const pNum = Number(rowObj.percentage);
        pctStr = `${pNum <= 1 ? Math.round(pNum * 100) : pNum}%`;
      }

      const totalFee = rowObj.totalAmount !== undefined ? `₹${rowObj.totalAmount}` : '';
      const paidFee = rowObj.paidAmount !== undefined ? `₹${rowObj.paidAmount}` : '';
      const pendingFee = rowObj.pendingAmount !== undefined ? `₹${rowObj.pendingAmount}` : '';
      const status = rowObj.status || '';

      if (data.reportType === 'fees' || data.reportType === 'pending_fees' || columns.includes('Pending Fee')) {
        rowValues = [sName, sCode, cName, dept, totalFee, paidFee, pendingFee, status];
      } else {
        rowValues = [sName, sCode, cName, dept, attended, total, pctStr];
      }
    }

    tableRows.push(
      new TableRow({
        children: columns.map((_, idx) => {
          const val = String(rowValues[idx] ?? '');
          return new TableCell({
            width: { size: Math.floor(100 / columns.length), type: WidthType.PERCENTAGE },
            margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [
              new Paragraph({
                alignment: idx >= 4 ? AlignmentType.RIGHT : AlignmentType.LEFT,
                children: [new TextRun({ text: val, size: 18, color: '1E293B' })],
              }),
            ],
          });
        }),
      })
    );
  });

  const docElements: any[] = [
    // Header Title
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: 'GRADit! College ERP Report', bold: true, size: 36, color: '1E1B4B' })],
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: data.subtitle || data.title || 'Summary Report', bold: true, size: 24, color: '4338CA' })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated By: ${data.generatedBy} | Date: ${data.generatedDate || new Date().toLocaleDateString()}`,
          italics: true,
          size: 20,
          color: '6B7280',
        }),
      ],
    }),
    new Paragraph({ text: '' }),
  ];

  // Metadata Card Block (if present)
  if (data.metadata && (data.metadata.studentName || data.metadata.studentCode || data.metadata.department || data.metadata.className)) {
    docElements.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun({ text: 'Student Information', bold: true, size: 22, color: '1E1B4B' })],
      }),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                shading: { fill: 'F1F5F9' },
                children: [new Paragraph({ children: [new TextRun({ text: 'Student Name', bold: true, size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                children: [new Paragraph({ children: [new TextRun({ text: data.metadata.studentName || 'N/A', size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                shading: { fill: 'F1F5F9' },
                children: [new Paragraph({ children: [new TextRun({ text: 'Student Code', bold: true, size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                children: [new Paragraph({ children: [new TextRun({ text: data.metadata.studentCode || 'N/A', size: 18 })] })],
              }),
            ],
          }),
          new TableRow({
            children: [
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                shading: { fill: 'F1F5F9' },
                children: [new Paragraph({ children: [new TextRun({ text: 'Class', bold: true, size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                children: [new Paragraph({ children: [new TextRun({ text: data.metadata.className || 'N/A', size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                shading: { fill: 'F1F5F9' },
                children: [new Paragraph({ children: [new TextRun({ text: 'Department', bold: true, size: 18 })] })],
              }),
              new TableCell({
                width: { size: 25, type: WidthType.PERCENTAGE },
                children: [new Paragraph({ children: [new TextRun({ text: data.metadata.department || 'N/A', size: 18 })] })],
              }),
            ],
          }),
        ],
      }),
      new Paragraph({ text: '' })
    );
  }

  // Add Summary Table
  docElements.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_3,
      children: [new TextRun({ text: 'Summary Table', bold: true, size: 22, color: '1E1B4B' })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: tableRows,
    }),
    new Paragraph({ text: '' }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: 'Confidential — GRADit! College ERP Report Service\nGenerated automatically by the ERP system.',
          italics: true,
          size: 16,
          color: '94A3B8',
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: docElements,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
