import ExcelJS from 'exceljs';
import { ReportData } from './types';

export async function generateExcelReportBuffer(data: ReportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'GRADit! ERP AI Chatbot Report Engine';
  workbook.created = new Date();

  const sheetName = data.reportType ? `${data.reportType.toUpperCase()} Report` : 'Attendance Report';
  const worksheet = workbook.addWorksheet(sheetName.substring(0, 31), {
    pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  });

  // 1. Title Banner
  worksheet.mergeCells('A1:G1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = 'GRADit! College ERP Report';
  titleCell.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FF1E1B4B' } };
  titleCell.alignment = { vertical: 'middle', horizontal: 'left' };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E7FF' } };
  worksheet.getRow(1).height = 30;

  // 2. Subtitle / Metadata Block
  worksheet.mergeCells('A2:G2');
  const subCell = worksheet.getCell('A2');
  subCell.value = data.subtitle || data.title || 'ERP Report Summary';
  subCell.font = { name: 'Arial', size: 12, bold: true, color: { argb: 'FF4338CA' } };
  subCell.alignment = { vertical: 'middle', horizontal: 'left' };
  worksheet.getRow(2).height = 22;

  // Metadata Fields
  worksheet.getCell('A3').value = 'Generated By:';
  worksheet.getCell('A3').font = { bold: true };
  worksheet.getCell('B3').value = data.generatedBy;

  worksheet.getCell('D3').value = 'Generated Date:';
  worksheet.getCell('D3').font = { bold: true };
  worksheet.getCell('E3').value = data.generatedDate || new Date().toLocaleDateString();

  if (data.metadata) {
    if (data.metadata.studentName) {
      worksheet.getCell('A4').value = 'Student Name:';
      worksheet.getCell('A4').font = { bold: true };
      worksheet.getCell('B4').value = data.metadata.studentName;
    }
    if (data.metadata.studentCode) {
      worksheet.getCell('D4').value = 'Student Code:';
      worksheet.getCell('D4').font = { bold: true };
      worksheet.getCell('E4').value = data.metadata.studentCode;
    }
    if (data.metadata.className) {
      worksheet.getCell('A5').value = 'Class:';
      worksheet.getCell('A5').font = { bold: true };
      worksheet.getCell('B5').value = data.metadata.className;
    }
    if (data.metadata.department) {
      worksheet.getCell('D5').value = 'Department:';
      worksheet.getCell('D5').font = { bold: true };
      worksheet.getCell('E5').value = data.metadata.department;
    }
  }

  worksheet.addRow([]); // Blank row spacer

  // 3. Table Headers Row (Row 7)
  const headerRowNumber = 7;
  const headerRow = worksheet.getRow(headerRowNumber);

  // Set explicit column headers
  const columns = data.columns && data.columns.length > 0
    ? data.columns
    : ['Student Name', 'Student Code', 'Class', 'Department', 'Attended', 'Total', 'Percentage'];

  headerRow.values = columns;
  headerRow.height = 26;

  headerRow.eachCell((cell) => {
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4338CA' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF312E81' } },
      bottom: { style: 'medium', color: { argb: 'FF1E1B4B' } },
      left: { style: 'thin', color: { argb: 'FF312E81' } },
      right: { style: 'thin', color: { argb: 'FF312E81' } },
    };
  });

  // 4. Data Rows
  data.rows.forEach((rowObj) => {
    let rowValues: any[] = [];

    if (Array.isArray(rowObj)) {
      rowValues = rowObj;
    } else {
      // Map typed object into columns
      const sName = rowObj.studentName || data.metadata?.studentName || '';
      const sCode = rowObj.studentCode || data.metadata?.studentCode || '';
      const cName = rowObj.className || data.metadata?.className || '';
      const dept = rowObj.department || data.metadata?.department || '';

      const attended = rowObj.attended !== undefined ? Number(rowObj.attended) : undefined;
      const total = rowObj.total !== undefined ? Number(rowObj.total) : undefined;

      let pctRatio: number | undefined = undefined;
      if (rowObj.percentage !== undefined) {
        const pNum = Number(rowObj.percentage);
        pctRatio = pNum > 1 ? pNum / 100 : pNum;
      }

      const totalFee = rowObj.totalAmount !== undefined ? Number(rowObj.totalAmount) : undefined;
      const paidFee = rowObj.paidAmount !== undefined ? Number(rowObj.paidAmount) : undefined;
      const pendingFee = rowObj.pendingAmount !== undefined ? Number(rowObj.pendingAmount) : undefined;
      const status = rowObj.status || '';

      if (data.reportType === 'fees' || data.reportType === 'pending_fees' || columns.includes('Pending Fee')) {
        rowValues = [sName, sCode, cName, dept, totalFee, paidFee, pendingFee, status];
      } else {
        rowValues = [sName, sCode, cName, dept, attended, total, pctRatio];
      }
    }

    const addedRow = worksheet.addRow(rowValues);
    addedRow.height = 20;

    addedRow.eachCell((cell, colNumber) => {
      cell.font = { name: 'Arial', size: 10 };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };

      const val = cell.value;
      if (typeof val === 'number') {
        cell.alignment = { vertical: 'middle', horizontal: 'right' };
        const colHeader = String(columns[colNumber - 1] || '').toLowerCase();

        if (colHeader.includes('percent') || colHeader.includes('%')) {
          cell.numFmt = '0.0%';
        } else if (colHeader.includes('fee') || colHeader.includes('amount') || colHeader.includes('paid') || colHeader.includes('pending')) {
          cell.numFmt = '₹#,##0';
        } else {
          cell.numFmt = '#,##0';
        }
      } else {
        cell.alignment = { vertical: 'middle', horizontal: 'left' };
      }
    });
  });

  // 5. Freeze Panes & AutoFilter
  const lastColLetter = String.fromCharCode(64 + Math.max(columns.length, 1));
  const lastRowNumber = worksheet.rowCount;
  worksheet.autoFilter = `A${headerRowNumber}:${lastColLetter}${lastRowNumber}`;
  worksheet.views = [{ state: 'frozen', xSplit: 0, ySplit: headerRowNumber }];

  // 6. Auto-fit column widths
  worksheet.columns.forEach((col) => {
    let maxLen = 15;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const len = cell.value ? String(cell.value).length : 0;
      if (len > maxLen) maxLen = len;
    });
    col.width = Math.min(Math.max(maxLen + 4, 14), 35);
  });

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
