import PDFDocument from 'pdfkit';
import { ReportData } from './types';

export type { ReportData } from './types';

export function generatePdfReportBuffer(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // 1. Header Banner
      doc.fillColor('#1e1b4b').font('Helvetica-Bold').fontSize(22).text('GRADit! College ERP Report', { align: 'left' });
      doc.moveDown(0.2);

      const subtitle = data.subtitle || data.title || 'Summary Report';
      doc.fillColor('#4338ca').font('Helvetica-Bold').fontSize(14).text(subtitle, { align: 'left' });
      doc.moveDown(0.3);

      doc.fillColor('#6b7280').font('Helvetica').fontSize(10).text(`Generated By: ${data.generatedBy} | Date: ${data.generatedDate || new Date().toLocaleDateString()}`);
      doc.moveDown(0.8);

      // Horizontal Divider Line
      doc.strokeColor('#e5e7eb').lineWidth(1.5).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
      doc.moveDown(0.8);

      // 2. Student / Report Metadata Block (if available)
      if (data.metadata && (data.metadata.studentName || data.metadata.studentCode || data.metadata.department || data.metadata.className)) {
        doc.fillColor('#111827').font('Helvetica-Bold').fontSize(12).text('Student Information', { align: 'left' });
        doc.moveDown(0.4);

        const metaStartY = doc.y;
        doc.rect(40, metaStartY, 515, 55).fillAndStroke('#f8fafc', '#e2e8f0');

        doc.fillColor('#334155').font('Helvetica-Bold').fontSize(10);
        doc.text('Student Name:', 52, metaStartY + 10);
        doc.font('Helvetica').text(data.metadata.studentName || 'N/A', 135, metaStartY + 10);

        doc.font('Helvetica-Bold').text('Student Code:', 300, metaStartY + 10);
        doc.font('Helvetica').text(data.metadata.studentCode || 'N/A', 385, metaStartY + 10);

        doc.font('Helvetica-Bold').text('Class:', 52, metaStartY + 32);
        doc.font('Helvetica').text(data.metadata.className || 'N/A', 135, metaStartY + 32);

        doc.font('Helvetica-Bold').text('Department:', 300, metaStartY + 32);
        doc.font('Helvetica').text(data.metadata.department || 'N/A', 385, metaStartY + 32);

        doc.y = metaStartY + 68;
        doc.moveDown(0.5);
      }

      // 3. Data Table Section
      doc.fillColor('#111827').font('Helvetica-Bold').fontSize(12).text('Summary Table', { align: 'left' });
      doc.moveDown(0.4);

      const tableTopY = doc.y;
      const totalWidth = 515;

      // Determine Column Widths
      const colCount = data.columns.length;
      let colWidths: number[] = [];

      if (colCount === 7) {
        // Standard Attendance Table: Name(125), Code(70), Class(75), Dept(65), Attended(55), Total(55), Pct(70)
        colWidths = [125, 70, 75, 65, 55, 55, 70];
      } else {
        const defaultWidth = Math.floor(totalWidth / colCount);
        colWidths = Array(colCount).fill(defaultWidth);
      }

      // Table Header Background
      doc.rect(40, tableTopY, totalWidth, 24).fill('#4338ca');

      // Table Header Text
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(9);
      let currentX = 40;
      data.columns.forEach((col, idx) => {
        doc.text(col, currentX + 4, tableTopY + 7, {
          width: colWidths[idx] - 8,
          align: idx >= 4 ? 'right' : 'left',
        });
        currentX += colWidths[idx];
      });

      let currentY = tableTopY + 24;

      // Table Rows
      doc.font('Helvetica').fontSize(9);
      data.rows.forEach((row, rIdx) => {
        if (currentY > 730) {
          doc.addPage();
          currentY = 40;
        }

        // Zebra striping
        if (rIdx % 2 === 1) {
          doc.rect(40, currentY, totalWidth, 20).fill('#f8fafc');
        }

        // Draw Row Line
        doc.strokeColor('#e2e8f0').lineWidth(0.5).moveTo(40, currentY + 20).lineTo(555, currentY + 20).stroke();

        doc.fillColor('#1e293b');
        let rowX = 40;

        const rowValues = Array.isArray(row)
          ? row
          : [
              row.studentName || data.metadata?.studentName || '',
              row.studentCode || data.metadata?.studentCode || '',
              row.className || data.metadata?.className || '',
              row.department || data.metadata?.department || '',
              row.attended !== undefined ? String(row.attended) : '',
              row.total !== undefined ? String(row.total) : '',
              row.percentage !== undefined
                ? `${typeof row.percentage === 'number' && row.percentage <= 1 ? Math.round(row.percentage * 100) : row.percentage}%`
                : '',
            ];

        data.columns.forEach((_, cIdx) => {
          const val = String(rowValues[cIdx] ?? '');
          doc.text(val, rowX + 4, currentY + 5, {
            width: colWidths[cIdx] - 8,
            align: cIdx >= 4 ? 'right' : 'left',
          });
          rowX += colWidths[cIdx];
        });

        currentY += 20;
      });

      // 4. Fixed Horizontal Footer (Prevents Vertical Character Squeezing)
      const footerY = doc.page.height - 40;
      doc.strokeColor('#cbd5e1').lineWidth(0.5).moveTo(40, footerY - 10).lineTo(555, footerY - 10).stroke();
      doc.fillColor('#94a3b8').font('Helvetica').fontSize(8);
      doc.text('Confidential — GRADit! College ERP Report Service', 40, footerY, {
        width: 515,
        align: 'center',
        lineBreak: false,
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
