export const REGEX_PATTERNS = {
  STUDENT_ID: /\b(?:\d{2}[A-Z]{2,4}\d{3}|STD-?\d{3,4}|[A-Z]{2,4}-?\d{3})\b/i,
  DEPARTMENT: /\b(?:CSE|ECE|MECH|EEE|IT|CIVIL|Computer\s+Science|Electronics|Mechanical|Electrical|Civil)\b/i,
  CLASS_ID: /\b(?:cls-[a-z0-9]+|23[a-z]{2}\d{3}|sec(?:tion)?\s*[a-z]|year\s*\d\s*sec\s*[a-z])\b/i,
  THRESHOLD: /(?:below|under|<|less\s+than|shortage\s+of)?\s*(\d{1,3})\s*(?:%|percent|percentage)?\b/i,
  SEMESTER: /\b(?:s([1-8])|sem(?:ester)?\s*([1-8])|([1-8])(?:st|nd|rd|th)?\s*sem(?:ester)?)\b/i,
  ACADEMIC_YEAR: /\b(20\d{2}[-/–]\d{2,4})\b/i,
  PAYMENT_STATUS: /\b(pending|unpaid|due|outstanding|paid|completed)\b/i,
  REPORT_FORMAT: /\b(pdf|excel|xlsx|spreadsheet|word|docx|document)\b/i,
  ATTENDANCE_KEYWORDS: /\b(attendance|present|absent|percentage|shortage|defaulter)\b/i,
  FEE_KEYWORDS: /\b(fee|fees|payment|paid|pending|due|balance|outstanding|unpaid|tuition)\b/i,
  STUDENT_DETAILS_KEYWORDS: /\b(details?|info|information|profile|student\s+details?|student\s+info|student\s+profile)\b/i,
  NAME_ATTENDANCE: /(?:attendance\s+(?:of|for)|show|get|check)\s+([a-z]+(?:\s+[a-z]+)?)\b/i,
  NAME_FEE: /(?:fee(?:s)?\s+(?:of|for|status|details)|paid\s+by)\s+([a-z]+(?:\s+[a-z]+)?)\b/i,
  NAME_SEARCH: /(?:find|search|lookup|details\s+of|details\s+for|show|get)\s+([a-z]+(?:\s+[a-z]+)?)\b/i,
};

export const DEPARTMENT_MAP: Record<string, string> = {
  'COMPUTER SCIENCE': 'CSE',
  'COMPUTER SCIENCE ENGINEERING': 'CSE',
  CSE: 'CSE',
  ELECTRONICS: 'ECE',
  ECE: 'ECE',
  MECHANICAL: 'MECH',
  MECH: 'MECH',
  ELECTRICAL: 'EEE',
  EEE: 'EEE',
  CIVIL: 'CIVIL',
  IT: 'IT',
};
